services:
    address_book.entity.repository_user:
        class: AddressBookBundle\Repository\UserRepository
        factory:
                - "@doctrine.orm.entity_manager"
                - getRepository
        arguments:
                - AddressBookBundle\Entity\User

    address_book.entity.repository_address:
        class: AddressBookBundle\Repository\AddressRepository
        factory:
                - "@doctrine.orm.entity_manager"
                - getRepository
        arguments:
                - AddressBookBundle\Entity\Address